---
# See:
#   - https://geekshare.net/resources/how-to-update-nginx-and-enable-http-2-support-on-debian-8-jessie.16/
#   - https://certbot.eff.org/#debianjessie-nginx

- name: Add circleci account to quartic group
  user: >
    name=circleci
    groups=quartic
    append=yes
  become: true

- name: Install packages
  apt: >
    name={{ item }}
    update_cache=yes
    default_release=jessie-backports
    state=present
  with_items:
    - nginx
    - nginx-extras
    - certbot
  become: true

- name: Create Nginx configuration
  copy: >
    src={{ item }}
    dest=/etc/nginx/{{ item }}
  with_items:
    - nginx.conf
    - ssl.conf
    - serve-without-suffix.conf
    - letsencrypt.conf
    - sites-available/default
    - .htpasswd
  become: true

- name: Check if we already have a cert
  stat: path=/etc/letsencrypt/live/{{ cert_directory }}/fullchain.pem
  register: cert
  become: true

# - name: Obtain cert
#   command: >
#     certbot certonly --webroot
#     -w /var/www/html {{ all_domains_for_certbot }}
#     --email={{ email }}
#     --agree-tos
#   when: cert.stat.exists == False
#   become: true

- name: Add cert-renewal cron job
  cron: >
    name="renew cert"
    cron_file=certbot
    user=root
    hour="1,13" minute="24"
    job="/usr/bin/certbot renew --quiet --no-self-upgrade && /usr/sbin/service nginx reload"
    state=present
  become: true

- name: Create DH params
  command: >
    openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
    creates=/etc/ssl/certs/dhparam.pem
  become: true

- name: Start Nginx service
  service: >
    name=nginx
    state=reloaded
    enabled=yes
  become: true
