---
name: demo
platform_version: "1326"
zeus_version: "257"
weyl:
  memory_gb: 8
  cpu: 3
  location:
    lat: 51.5174
    lng: -0.0915
    zoom: 9.7
dataset_categories:
  - small
  - large
  - live
auth_secret: |
  admin:$apr1$gH1mEO/e$WVAD6tU4dfzzzaxFOpaoz1
