---
name: magnolia
codename: dozers
platform_version: "1315"
zeus_version: "205"
weyl:
  memory_gb: 8
  cpu: 3
  location:
    lat: 51.4679
    lng: -0.3548
    zoom: 11.7
dataset_categories:
  - small
auth_secret: |
  magnolia:$apr1$uLBPrnGd$LygxsA2JyhS8f.jxJt10E.
  yogesh.patel:$apr1$KmvOtgmJ$5iTqLSCTmbzvzlHnMGR/a.
  sebastien.magat:$apr1$MCsVbqHi$.FYsHBJUUZUCr7HmmRhBh/
  tim.hurley:$apr1$O7bJA1J.$egy3al/ZO4XlFk62qa33g.
  satbir.gill:$apr1$WNioQJc9$R0hvgqArHZw1d93PDgJxF.
  damon.pass:$apr1$/UwftpFh$RKz05KyJ8ieTe2AvE5bKO1
  karim.hamza:$apr1$Bj/Xo6Sw$WncEeXg4MMkPsQgbq.VUO1