---
name: revolut
platform_version: 0.2.0-472-gb327be6
weyl:
  memory_gb: 4
  cpu: 2
management:
  memory_mb: 128 
dataset_categories:
  - small
auth_secret: cmV2b2x1dDokYXByMSQ3cFFqTHQ2YiR5a20ybGZaNTRHeGF6ZmMwYnhndjQxCg==
