apiVersion: v1
data:
  alert.rules: |
    ALERT service_down
      IF up == 0

    ALERT high_load
      IF node_load1 > 0.5
      ANNOTATIONS {
          summary = "Instance {{ $labels.instance }} under high load",
          description = "{{ $labels.instance }} of job {{ $labels.job }} is under high load.",
      }
  prometheus.yml: |
    # my global config
    global:
      scrape_interval:     15s # By default, scrape targets every 15 seconds.
      evaluation_interval: 15s # By default, scrape targets every 15 seconds.
      # scrape_timeout is set to the global default (10s).

      # Attach these labels to any time series or alerts when communicating with
      # external systems (federation, remote storage, Alertmanager).
      external_labels:
          monitor: 'platform'

    # Load and evaluate rules in this file every 'evaluation_interval' seconds.
    rule_files:
      - "alert.rules"
      # - "first.rules"
      # - "second.rules"

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: 'prometheus'

        # Override the global default and scrape targets from this job every 5 seconds.
        scrape_interval: 5s

        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.

        static_configs:
             - targets: ['localhost:9090']
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]  # Look for a HTTP 200 response.
        static_configs:
          - targets:
              - "weyl:8081"
              - "catalogue:8091"
              - "my-balls"
        relabel_configs:
          - source_labels: [__address__]
            regex: (.*)(:80)?
            target_label: __param_target
            replacement: ${1}
          - source_labels: [__param_target]
            regex: (.*)
            target_label: instance
            replacement: ${1}
          - source_labels: []
            regex: .*
            target_label: __address__
            replacement: localhost:9115  # Blackbox exporter.
kind: ConfigMap
metadata:
  namespace: platform
  name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: platform
  name: blackbox-config
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [] # Defaults to 2xx
          method: GET
          headers:
            Accept-Language: en-US
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          fail_if_matches_regexp:
          - "Could not connect to database"
          fail_if_not_matches_regexp:
          - "Download the latest version here"
      http:
        prober: http
        timeout: 15s
        http:
          valid_status_codes: []
          method: GET
---
apiVersion: v1
data:
  config.yml: |-
    route:
        receiver: 'slack'

    receivers:
        - name: 'slack'
          slack_configs:
              - send_resolved: true
                username: '<username>'
                channel: '#<channel-name>'
                api_url: '<incomming-webhook-url>'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: platform
  labels:
    component: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    protocol: TCP
  selector:
    component: prometheus
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: prometheus
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - '-config.file=/etc/prometheus/prometheus.yml'
            - '-storage.local.path=/prometheus'
            - '-alertmanager.url=http://alertmanager:9093'
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
        - name: blackbox
          image: prom/blackbox-exporter
          args:
            - '-config.file=/etc/blackbox/blackbox.yml'
          ports:
            - containerPort: 9115
          volumeMounts:
            - name: blackbox-config-volume
              mountPath: /etc/blackbox
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: blackbox-config-volume
          configMap:
            name: blackbox-config
        - name: data
          emptyDir: {}
