version: 2

references:

  defaults: &defaults
    working_directory: ~/infra
    docker:
      - image: hashicorp/terraform:0.10.6
        environment:
          TF_IN_AUTOMATION: 1

  tf_init: &tf_init
    command: |
      export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)
      terraform init -input=false

  tf_plan: &tf_plan
    command: |
      export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)
      terraform plan -input=false -out=tfplan

  tf_apply: &tf_apply
    command: |
      export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)
      terraform apply -input=false tfplan


jobs:
  plan:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Init (global)
          working_directory: terraform/global
          <<: *tf_init
      - run:
          name: Init (staging)
          working_directory: terraform/staging
          <<: *tf_init
      - run:
          name: Init (prod)
          working_directory: terraform/prod
          <<: *tf_init

      - run:
          name: Plan (global)
          working_directory: terraform/global
          <<: *tf_plan
      - run:
          name: Plan (staging)
          working_directory: terraform/staging
          <<: *tf_plan
      - run:
          name: Plan (prod)
          working_directory: terraform/prod
          <<: *tf_plan

      - persist_to_workspace:
          root: terraform/
          paths:
            - "**/tfplan"


  apply_global:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: terraform/
      
      - run:
          name: Init (global)
          working_directory: terraform/global
          <<: *tf_init

      - deploy:
          name: Apply (global)
          working_directory: terraform/global
          <<: *tf_apply


  apply_staging:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: terraform/

      - run:
          name: Init (staging)
          working_directory: terraform/staging
          <<: *tf_init

      - deploy:
          name: Apply (staging)
          working_directory: terraform/staging
          <<: *tf_apply


  apply_prod:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: terraform/
      
      - run:
          name: Init (prod)
          working_directory: terraform/prod
          <<: *tf_init

      - deploy:
          name: Apply (prod)
          working_directory: terraform/prod
          <<: *tf_apply


workflows:
  version: 2

  # TODO - add filtering
  plan_and_apply:
    jobs:
      - plan
      - hold:
          type: approval
          requires:
            - plan
      - apply_global:
          requires:
            - hold
      - apply_staging:
          requires:
            - plan
      - apply_prod:
          requires:
            - apply_global