version: 2

references:

  defaults: &defaults
    working_directory: ~/infra
    docker:
      - image: hashicorp/terraform:0.10.6
        environment:
          TF_IN_AUTOMATION: 1

  tf_init: &tf_init terraform init -input=false
  tf_plan: &tf_plan terraform plan -input=false -out=tfplan
  tf_apply: &tf_apply terraform apply -input=false tfplan


jobs:
  plan:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Init (global)
          working_directory: terraform/global
          command: *tf_init
      - run:
          name: Init (staging)
          working_directory: terraform/staging
          command: *tf_init
      - run:
          name: Init (prod)
          working_directory: terraform/prod
          command: *tf_init

      - run:
          name: Plan (global)
          working_directory: terraform/global
          command: *tf_plan
      - run:
          name: Plan (staging)
          working_directory: terraform/staging
          command: *tf_plan
      - run:
          name: Plan (prod)
          working_directory: terraform/prod
          command: *tf_plan

      - persist_to_workspace:
          root: terraform/
          paths:
            - "**/tfplan"


  apply_global:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: terraform/
      
      - run:
          name: Init (global)
          working_directory: terraform/global
          command: *tf_init

      - deploy:
          name: Apply (global)
          working_directory: terraform/global
          command: *tf_apply


  apply_staging:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: terraform/

      - run:
          name: Init (staging)
          working_directory: terraform/staging
          command: *tf_init

      - deploy:
          name: Apply (staging)
          working_directory: terraform/staging
          command: *tf_apply


  apply_prod:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: terraform/
      
      - run:
          name: Init (prod)
          working_directory: terraform/prod
          command: *tf_init

      - deploy:
          name: Apply (prod)
          working_directory: terraform/prod
          command: *tf_apply


workflows:
  version: 2

  plan_and_apply:
    jobs:
      - plan
 
      # No approval needed for staging - triggered by merge to develop

      - apply_staging:
          requires:
            - plan
          filters:
            branches:
              only: develop

      # Approval needed for prod - triggered by merge to master

      - hold:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: master

      - apply_global:
          requires:
            - hold
          filters:
            branches:
              only: master

      - apply_prod:
          requires:
            - apply_global
          filters:
            branches:
              only: master


experimental:
  notify:
    branches:
      only:
        - develop
