version: 2

defaults: &defaults
  working_directory: ~/infra
  docker:
    - image: hashicorp/terraform:0.10.6
      environment:
        TF_IN_AUTOMATION: 1

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Terraform init
          working_directory: terraform
          command: |
            export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)

            for cfg in global staging prod; do
              cd ${cfg}
              terraform init
              cd -
            done

      - run:
          name: Terraform plan
          working_directory: terraform
          command: |
            export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)

            for cfg in global staging prod; do
              cd ${cfg}
              terraform plan
              cd -
            done

      - persist_to_workspace:
          root: .
          paths:
            - terraform/

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - deploy:
          name: Terraform apply
          working_directory: terraform
          command: |
            echo "I'm a noob"
            ls -l
            # if [ "${CIRCLE_BRANCH}" == "master" ]; then
            #   export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)

            #   for cfg in global staging prod; do
            #     cd ${cfg}
            #     terraform apply
            #     cd -
            #   done
            # fi

workflows:
  version: 2

  # TODO - add filtering
  build_and_deploy:
    jobs:
      - build
      # - hold:
      #     type: approval
      #     requires:
      #       - build
      - deploy:
          requires:
            - build
            # - hold