version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.10.6
        environment:
          TF_IN_AUTOMATION: 1

    working_directory: ~/infra

    steps:
      - checkout

      - run:
          name: Terraform init
          working_directory: terraform/reality
          command: |
            export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)

            for cfg in global staging prod; do
              cd ${cfg}
              terraform init
              cd -
            done

      - run:
          name: Terraform plan
          working_directory: terraform/reality
          command: |
            export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)

            for cfg in global staging prod; do
              cd ${cfg}
              terraform plan
              cd -
            done


      - deploy:
          name: Terraform apply
          working_directory: terraform/reality
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)

              for cfg in global staging prod; do
                cd ${cfg}
                terraform apply
                cd -
              done
            fi
