version: 2

references:

  defaults: &defaults
    working_directory: ~/infra
    docker:
      - image: hashicorp/terraform:0.10.6
        environment:
          TF_IN_AUTOMATION: 1

  tf_plan: &tf_plan |
    terraform init -input=false -reconfigure -backend-config="path=${ENV}/terraform.tfstate" 
    terraform plan -input=false -var-file=${ENV}.tfvars -out=${ENV}.tfplan

  tf_plan_destroy: &tf_plan_destroy |
    terraform init -input=false -reconfigure -backend-config="path=${ENV}/terraform.tfstate" 
    terraform plan -input=false -var-file=${ENV}.tfvars -out=${ENV}.tfplan -destroy

  tf_apply: &tf_apply |
    terraform init -input=false -reconfigure -backend-config="path=${ENV}/terraform.tfstate" 
    terraform apply -input=false ${ENV}.tfplan 


jobs:
  plan:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Plan - Global
          working_directory: terraform/global
          environment: { ENV: "global" }
          command: *tf_plan

      - run:
          name: Plan - Dev
          working_directory: terraform/env
          environment: { ENV: "dev" }
          command: *tf_plan_destroy     # DESTROY!!!

      - run:
          name: Plan - Staging
          working_directory: terraform/env
          environment: { ENV: "staging" }
          command: *tf_plan_destroy     # DESTROY!!!

      - run:
          name: Plan - Prod
          working_directory: terraform/env
          environment: { ENV: "prod" }
          command: *tf_plan_destroy     # DESTROY!!!

      - persist_to_workspace:
          root: terraform/
          paths:
            - "**/*.tfplan"


  apply_global:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: terraform/

      - deploy:
          name: Apply - Global
          working_directory: terraform/global
          environment: { ENV: "global" }
          command: *tf_apply


  apply_dev:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: terraform/

      - deploy:
          name: Apply - Dev
          working_directory: terraform/env
          environment: { ENV: "dev" }
          command: *tf_apply


  apply_staging:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: terraform/

      - deploy:
          name: Apply - Staging
          working_directory: terraform/env
          environment: { ENV: "staging" }
          command: *tf_apply


  apply_prod:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: terraform/

      - deploy:
          name: Apply - Prod
          working_directory: terraform/env
          environment: { ENV: "prod" }
          command: *tf_apply


workflows:
  version: 2

  plan_and_apply:
    jobs:
      - plan

      # No approval needed for dev / staging

      - apply_dev:
          requires:
            - plan
          filters:
            branches:
              only: develop

      - apply_staging:
          requires:
            - plan
          filters:
            branches:
              only: develop

      # Approval needed for prod

      - hold:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: develop

      - apply_global:
          requires:
            - hold
          filters:
            branches:
              only: develop

      - apply_prod:
          requires:
            - apply_global
          filters:
            branches:
              only: develop


experimental:
  notify:
    branches:
      only:
        - develop
