version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.10.4

    working_directory: ~/infra

    steps:
      - checkout

      - run:
          name: Terraform init
          working_directory: terraform/staging
          command: |
            export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)
            terraform init

      - run:
          name: Terraform plan
          working_directory: terraform/staging
          command: |
            export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)
            terraform plan

      - deploy:
          name: Terraform apply
          working_directory: terraform/staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)
              terraform apply
            fi
