version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.10.4

    working_directory: ~/infra

    steps:
      - checkout

      # TODO - all of this now needs to run in multiple workspace folders

      - run:
          name: Terraform init
          working_directory: terraform
          command: |
            export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)

            cd global
            terraform init
            cd -

            cd staging
            terraform init
            cd -


      - run:
          name: Terraform plan
          working_directory: terraform/staging
          command: |
            export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)

            cd global
            terraform plan
            cd -

            cd staging
            terraform init
            cd -


      - deploy:
          name: Terraform apply
          working_directory: terraform/staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export GOOGLE_CREDENTIALS=$(echo ${GOOGLE_CREDENTIALS_BASE64} | base64 -d)

              cd global
              terraform apply
              cd -

              cd staging
              terraform apply
              cd -
            fi
