version: '2'
services:
  postgis:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dilectic

  tayo:
    image: eu.gcr.io/quartic-oliver/tayo:0.1.0

  nginx:
    image: nginx
    ports:
      - "${FRONT_DOOR_PORT}:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ${DATASETS_DIRECTORY}:/datasets
    links:
      - tayo
