version: '2'
services:
  postgis:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dilectic

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /opt/quartic/datasets:/var/www/html
