---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "ingress"
labels:
  template: "ingress-template"
parameters:
  - name: "DOMAIN_NAME"
    description: "Domain name"
    required: true
    parameterType: "string"
objects:

  #----------------#
  # core
  #----------------#
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: ingress
      namespace: core
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        ingress.kubernetes.io/auth-type: basic
        ingress.kubernetes.io/auth-secret: basic-auth
    spec:
      tls:
        - secretName: tls-core
          hosts:
            - "core.$(DOMAIN_NAME)"
      rules:
        - host: "core.$(DOMAIN_NAME)"
          http:
            paths:
              - path: /
                backend:
                  serviceName: grafana
                  servicePort: 3000

  #----------------#
  # platform
  #----------------#
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: ingress
      namespace: platform
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        ingress.kubernetes.io/auth-type: basic
        ingress.kubernetes.io/auth-secret: basic-auth
    spec:
      tls:
        - secretName: tls-alpha
          hosts:
            - "alpha.$(DOMAIN_NAME)"
        - secretName: tls-mgmt
          hosts:
            - "mgmt.$(DOMAIN_NAME)"
      rules:
        - host: "alpha.$(DOMAIN_NAME)"
          http:
            paths:
              - path: /
                backend:
                  serviceName: weyl
                  servicePort: 8080
        - host: "mgmt.$(DOMAIN_NAME)"
          http:
            paths:
              - path: /
                backend:
                  serviceName: management
                  servicePort: 8100

  #----------------#
  # dilectic
  #----------------#
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: ingress
      namespace: dilectic
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
    spec:
      tls:
        - secretName: tls-tracker
          hosts:
            - "tracker.$(DOMAIN_NAME)"
      rules:
        - host: "tracker.$(DOMAIN_NAME)"
          http:
            paths:
              - path: /upload
                backend:
                  serviceName: tracker
                  servicePort: 8080
