apiVersion: v1
kind: Service
metadata:
  name: formistry
  labels:
    component: formistry
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: default
  selector:
    component: formistry
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: formistry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: formistry
    spec:
      containers:
        - name: formistry
          image: {{cluster.gcloud_docker_repository}}/formistry:{{cluster.formistry_version}}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m