apiVersion: v1
kind: Service
metadata:
  name: www
  namespace: www
  labels:
    component: www
spec:
  ports:
  - port: 80
    protocol: TCP
    name: default
  selector:
    component: www
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: www
  namespace: www
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: www
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: core
      containers:
        - name: www
          # CI is deploying latest via specific version tag, but if we ever reprovision then just grab latest as a fallback
          image: {{cluster.gcloud.docker_repository}}/website:{{cluster.www.default_website_tag}}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
