apiVersion: v1
kind: Service
metadata:
  name: www
  labels:
    component: www
spec:
  ports:
  - port: 80
    protocol: TCP
    name: default
  selector:
    component: www
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: www
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: www
    spec:
      containers:
        - name: www
          # CI is deploying latest via specific version tag, but if we ever reprovision then just grab "latest"
          image: {{cluster.gcloud_docker_repository}}/website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
