org_id                      = "2425379824"
billing_account             = "00798C-5FD4EC-188617"
region                      = "europe-west2"
project_name                = "Quartic - Staging env"
viewer_group                = "core@quartic.io"
dns_name                    = "quartic.io."
cluster_name                = "staging"
cluster_core_node_count     = 1
cluster_worker_node_count   = 1