#! /bin/bash
set -eu
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function kill_pf() {
    local port=${1}
    ps -ef | grep port-forward | grep ${port} | awk '{print $2}' | xargs kill -9
}

kill_pf 8090
kill_pf 8120

kubectl port-forward -n platform `${DIR}/get-pod platform catalogue` 8090 &
kubectl port-forward -n platform `${DIR}/get-pod platform howl` 8120 &