apiVersion: v1
data:
  start.sh: |
    set -e
    mkdir ./bucket
    gcsfuse -o nonempty quartictech ./bucket
    cd ./bucket/jupyter/bokeh-dashboards
    bokeh serve --use-xheaders --prefix=dashboards --host=core.{{cluster.domain_name}} --allow-websocket-origin=core.{{cluster.domain_name}} `find . -name "main.py" -exec dirname {} \;`
kind: ConfigMap
metadata:
  name: start
  namespace: core
---
apiVersion: v1
kind: Service
metadata:
  name: bokeh
  namespace: core
  labels:
    component: bokeh
spec:
  ports:
  - port: 5006
    protocol: TCP
    name: default
  selector:
    component: bokeh
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: bokeh
  namespace: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: bokeh
    spec:
      containers:
        - name: bokeh
          image: eu.gcr.io/quartictech/taijitu:11
          ports:
            - containerPort: 5006
          resources:
            requests:
              cpu: 1
              memory: 1Gi
          securityContext:
            privileged: true
            capabilities:
                add:
                  - SYS_ADMIN
          lifecycle:
            preStop:
              exec:
                command: ["fusermount", "-u", "/bucket"]
          volumeMounts:
            - name: config-volume
              mountPath: /setup
          command: ["sh", "/setup/start.sh"]
      volumes:
        - name: config-volume
          configMap:
            name: start

