apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    component: grafana
  name: grafana
  namespace: core
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    component: grafana
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        component: grafana
    spec:
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      containers:
      - name: grafana
        image: kubernetes/heapster_grafana:v2.6.0
        ports:
          - containerPort: 3000
            protocol: TCP
        resources:
          limits:
            cpu: 100m
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
        - mountPath: /dashboards
          name: grafana-dashboards
        env:
        - name: INFLUXDB_HOST
          value: influxdb
        - name: INFLUXDB_PORT
          value: "8086"
        - name: GRAFANA_PORT
          value: "3000"
          # The following env variables are required to make Grafana accessible via
          # the kubernetes api-server proxy. On production clusters, we recommend
          # removing these env variables, setup auth for grafana, and expose the grafana
          # service using a LoadBalancer or a public IP.
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          # value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
          value: /
