---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: core
data:
  X-Forwarded-User: $remote_user
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-load-balancer-conf
  namespace: core
data:
  proxy-body-size: 250m
  proxy-set-headers: "core/custom-headers"
---
# TODO: convert to DaemonSet once we have more than one cluster node
apiVersion: v1
kind: ReplicationController
metadata:
  name: ingress-controller
  namespace: core
  labels:
    component: ingress-controller
spec:
  replicas: 1
  selector:
    component: ingress-controller
  template:
    metadata:
      labels:
        component: ingress-controller
        namespace: core
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.7
        name: nginx-ingress-lb
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        # use downward API
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        resources:
          limits:
            cpu: 100m
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --configmap=$(POD_NAMESPACE)/nginx-load-balancer-conf
