apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: core
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth

spec:
  tls:
    - secretName: tls-core
      hosts:
        - core.{{cluster.domain_name}}

  rules:
    - host: core.{{cluster.domain_name}}
      http:
        paths:
          - path: /prometheus
            backend:
              serviceName: prometheus
              servicePort: 9090
          - path: /alertmanager
            backend:
              serviceName: prometheus
              servicePort: 9093
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000

