apiVersion: v1
kind: Service
metadata:
  name: ingress-controller
  namespace: core
spec:
  type: LoadBalancer
  loadBalancerIP: {{cluster.gcloud.static_ip}}
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    component: ingress-controller
