apiVersion: v1
kind: PersistentVolume
metadata:
  name: metabase-data
  namespace: core
  labels:
    name: metabase-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    # TODO - parameterise this
    pdName: prod-metabase
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metabase-data-claim
  namespace: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: core
  labels:
    component: metabase
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: default
  selector:
    component: metabase
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: metabase
  namespace: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
          env:
            - name: MB_DB_FILE
              value: /tmp/metabase.db
          volumeMounts:
            - name: metabase-data
              mountPath: /tmp
          resources:
            limits:
              cpu: 1
              memory: 2Gi
      volumes:
        - name: metabase-data
          persistentVolumeClaim:
            claimName: metabase-data-claim