---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slack8s
  namespace: core
data:
  slack-token: "xoxb-102863698592-HFFlZWB9GnmIWoLybMDuhPxv"
  slack-channel: "#kubernetes"
  slack-botid: "slack8s"
---
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: slack8s
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack8s
  strategy:
    type: Recreate
  template:
    metadata:
      name: slack8s
      labels:
        app: slack8s
      namespace: slack8s
    spec:
      containers:
        - name: slack8s
          image: ultimateboy/slack8s
          imagePullPolicy: Always
          env:
            - name: SLACK_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: slack8s
                  key: slack-token
            - name: SLACK_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: slack8s
                  key: slack-channel
        - name: kube-proxy
          image: gcr.io/google_containers/kubectl:v0.18.0-120-gaeb4ac55ad12b1-dirty
          imagePullPolicy: Always
          args: ["proxy", "-p", "8001"]
