apiVersion: v1
data:
  install.sh: |
    set -e
    apt-get update && apt-get install -y curl
    echo "deb http://packages.cloud.google.com/apt gcsfuse-xenial main" | tee /etc/apt/sources.list.d/gcsfuse.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    apt-get update && apt-get install -y gcsfuse
    mkdir /bucket
    gcsfuse -o nonempty quartictech /bucket
    
    # TODO - real stuff goes here
    tail -f /dev/null
kind: ConfigMap
metadata:
  name: start
  namespace: noobery
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: noob
  namespace: noobery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: noob
    spec:
      containers:
        - name: noob
          image: ubuntu:latest
          securityContext:
            privileged: true
            capabilities:
                add:
                  - SYS_ADMIN
          lifecycle:
            preStop:
              exec:
                command: ["fusermount", "-u", "/bucket"]
          volumeMounts:
            - name: config-volume
              mountPath: /setup
          command: ["sh", "/setup/install.sh"]
      volumes:
        - name: config-volume
          configMap:
            name: start
