apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: noobery
  labels:
    component: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: default
  selector:
    component: redis
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: redis
  namespace: noobery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:3.0-alpine
          ports:
            - containerPort: 6379