apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: platform
  labels:
    component: catalogue
spec:
  ports:
  - port: 8090
    protocol: TCP
  selector:
    component: catalogue
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: catalogue
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: catalogue
    spec:
      containers:
        - name: catalogue
          image: eu.gcr.io/quartictech/catalogue:0.2.0-143-g6db5433
          ports:
            - containerPort: 8090
            - containerPort: 8091
