apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: platform
  labels:
    component: catalogue
spec:
  ports:
  - port: 8090
    protocol: TCP
    name: default
  - port: 8091
    protocol: TCP
    name: admin
  selector:
    component: catalogue
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: catalogue
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: catalogue
    spec:
      containers:
        - name: catalogue
          image: eu.gcr.io/quartictech/catalogue:0.2.0-423-gdf90938
          ports:
            - containerPort: 8090
            - containerPort: 8091
          env:
            - name: ENABLE_METRICS
            - name: INFLUX_HOST
              value: influxdb.core
            - name: INFLUX_PORT
              value: "8086"
            - name: INFLUX_DB
              value: k8s
            - name: INFLUX_AUTH
              value: root:root
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
