apiVersion: v1
kind: Service
metadata:
  name: docs
  namespace: platform
  labels:
    component: docs
spec:
  ports:
  - port: 80
    protocol: TCP
    name: default
  selector:
    component: docs
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: docs
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: docs
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: core
      containers:
        - name: docs
          image: eu.gcr.io/quartictech/docs:{{cluster.platform_version}}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m