apiVersion: v1
data:
  config.yml: |
    registryUrl: http://registry:8190/api

    qube:
      url: ws://qube:8202
      container:
        image: eu.gcr.io/quartictech/jupyter:53
        command:
          - "sleep"
          - "1000"

    github:
      appId: 3853
      apiRootUrl: https://api.github.com
      privateKeyEncrypted: {{cluster.secrets.github_private_key}}

    url:
      port: 8210
   
kind: ConfigMap
metadata:
  namespace: platform
  name: eval-config
---
apiVersion: v1
kind: Service
metadata:
  name: eval
  namespace: platform
  labels:
    component: eval
  annotations:
    quartic.io/healthcheck_path: /healthcheck
    quartic.io/healthcheck_port: "8211"
spec:
  ports:
  - port: 8210
    protocol: TCP
    name: default
  - port: 8211
    protocol: TCP
    name: admin
  selector:
    component: eval
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: eval
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: eval
    spec:
      containers:
        - name: eval
          image: eu.gcr.io/quartictech/eval:{{cluster.platform_version}}
          ports:
            - containerPort: 8210
            - containerPort: 8211
          env:
            - name: MASTER_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: master_key_base64
          volumeMounts:
            - name: config
              mountPath: /service/config.yml
              subPath: config.yml
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: "config"
          configMap:
            name: "eval-config"