apiVersion: v1
data:
  config.yml: |
    catalogueUrl: http://catalogue:8090/api
    howlUrl: http://howl:8120/api
    registryUrl: http://registry:8190/api
    qubeUrl: http://qube:8200/api

    github:
      clientId: "ab6d4546d3895f750518"
      clientSecretEncrypted: {{cluster.secrets.github_client_secret}}
      trampolineUrl: "https://api.quartic.io/api/auth/gh/callback"
      redirectHost: "https://%s.quartic.io"
      scopes: [user]

    cookies:
      secure: true
      maxAgeSeconds: 2592000 # 30 days

    auth:
      type: token
      keyEncryptedBase64: {{cluster.secrets.token_signing_key}}

    url:
      port: 8100
    
kind: ConfigMap
metadata:
  namespace: platform
  name: home-config
---
apiVersion: v1
kind: Service
metadata:
  name: home
  namespace: platform
  labels:
    component: home
  annotations:
    quartic.io/healthcheck_path: /healthcheck
    quartic.io/healthcheck_port: "8101"
spec:
  ports:
  - port: 8100
    protocol: TCP
    name: default
  - port: 8101
    protocol: TCP
    name: admin
  selector:
    component: home
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: home
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: home
    spec:
      containers:
        - name: home
          image: eu.gcr.io/quartictech/home:{{cluster.platform_version}}
          ports:
            - containerPort: 8100
            - containerPort: 8101
          env:
            - name: MASTER_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: master_key_base64
          volumeMounts:
            - name: config
              mountPath: /service/config.yml
              subPath: config.yml
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: "config"
          configMap:
            name: "home-config"