apiVersion: v1
kind: Service
metadata:
  name: howl
  namespace: {{stack.name}}
  labels:
    component: howl
  annotations:
    quartic.io/healthcheck_path: /healthcheck
    quartic.io/healthcheck_port: "8121"
spec:
  ports:
  - port: 8120
    protocol: TCP
    name: default
  - port: 8121
    protocol: TCP
    name: admin
  selector:
    component: howl
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: howl
  namespace: {{stack.name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: howl
    spec:
      containers:
        - name: howl
          image: eu.gcr.io/quartictech/howl:{{stack.platform_version}}
          ports:
            - containerPort: 8120
            - containerPort: 8121
          env:
            - name: HOWL_APPLICATION_OPTS
              value: >
                -Ddw.storage.type=google_cloud_storage
                -Ddw.storage.bucketName={{stack.name}}.{{cluster.datastore_namespace_prefix}}.quartic.io
            - name: ENABLE_METRICS
            - name: INFLUX_HOST
              value: influxdb.core
            - name: INFLUX_PORT
              value: "8086"
            - name: INFLUX_DB
              value: k8s
            - name: INFLUX_AUTH
              value: root:root
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 100m
