apiVersion: v1
data:
  config.yml: |
    aws:
      region: {{cluster.aws.region}}
      access_key_id: {{cluster.aws.access_key_id}}
      secret_access_key_encrypted: {{cluster.aws.secret_access_key_encrypted}}

    # TODO: this is obviously nonsense in the long run
    namespaces:
    {% for cust_name, cust_details in cluster.customers.items() %}
      {{cust_name|indent(6)}}:
        {{cust_details.howl|indent(8)}}
    {% endfor %}

    url:
      port: 8120

kind: ConfigMap
metadata:
  namespace: platform
  name: howl-config
---
apiVersion: v1
kind: Service
metadata:
  name: howl
  namespace: platform
  labels:
    component: howl
  annotations:
    quartic.io/healthcheck_path: /healthcheck
    quartic.io/healthcheck_port: "8121"
spec:
  ports:
  - port: 8120
    protocol: TCP
    name: default
  - port: 8121
    protocol: TCP
    name: admin
  selector:
    component: howl
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: howl
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: howl
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: core
      containers:
        - name: howl
          image: eu.gcr.io/quartictech/howl:{{cluster.platform_version}}
          ports:
            - containerPort: 8120
            - containerPort: 8121
          env:
            - name: MASTER_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: master_key_base64
          volumeMounts:
            - name: config
              mountPath: /service/config.yml
              subPath: config.yml
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: "config"
          configMap:
            name: "howl-config"