apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    component: influxdb
  name: monitoring-influxdb
  namespace: platform
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8083
  - name: api
    port: 8086
    targetPort: 8086
  selector:
    component: influxdb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        component: influxdb
    spec:
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      containers:
      - name: influxdb
        image: tutum/influxdb:0.13
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        env:
          - name: PRE_CREATE_DB
            value: k8s
