apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-basic-auth
  namespace: platform
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth
spec:
  tls:
    - secretName: tls-platform-docs
      hosts:
        - docs.{{cluster.domain_name}}
  rules:
    - host: docs.{{cluster.domain_name}}
      http:
        paths:
          - path: /
            backend:
              serviceName: docs
              servicePort: 80