apiVersion: v1
data:
  mgmt.yml: |
    catalogueUrl: http://catalogue:8090/api
    howlUrl: http://howl:8120/api
    authorisedNamespaces:
      admin: ["*"]
    github:
      clientId: "ab6d4546d3895f750518"
      clientSecret: "211501cfe34b15d53ce131b4f9f6d7f690cc7984"
      allowedOrganisations:
        - quartictech
      trampolineUrl: "https://api.quartic.io/api/auth/gh/callback"

      #redirectHost: "http://localhost:3010"
      # in prod this should be
      redirectHost: "https://%s.quartic.io"

      useSecureCookies: true
      cookieMaxAgeSeconds: 2592000 # 30 days
      scopes:
        - user

    server:
      applicationContextPath: /
      applicationConnectors:
        - type: http
          port: 8100
      adminConnectors:
        - type: http
          port: 8101
    auth:
      type: token
      base64EncodedKey: "BffwOJzi7ejTe9yC1IpQ4+P6fYpyGz+GvVyrfhamNisNqa96CF8wGSp3uATaITUP7r9n6zn9tDN8k4424zwZ2Q=="

    
kind: ConfigMap
metadata:
  namespace: platform
  name: mgmt-config
---
apiVersion: v1
kind: Service
metadata:
  name: mgmt
  namespace: platform
  labels:
    component: mgmt
  annotations:
    quartic.io/healthcheck_path: /healthcheck
    quartic.io/healthcheck_port: "8101"
spec:
  ports:
  - port: 8100
    protocol: TCP
    name: default
  - port: 8101
    protocol: TCP
    name: admin
  selector:
    component: mgmt
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mgmt
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: mgmt
    spec:
      containers:
        - name: mgmt
          image: eu.gcr.io/quartictech/mgmt:{{cluster.platform_version}}
          ports:
            - containerPort: 8100
            - containerPort: 8101
          volumeMounts:
            - name: config
              mountPath: /mgmt-application-{{cluster.platform_version}}/mgmt.yml
              subPath: mgmt.yml
          env:
            - name: ENABLE_METRICS
            - name: INFLUX_HOST
              value: influxdb.core
            - name: INFLUX_PORT
              value: "8086"
            - name: INFLUX_DB
              value: k8s
            - name: INFLUX_AUTH
              value: root:root
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: "config"
          configMap:
            name: "mgmt-config"