apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: platform
  labels:
    component: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    component: nginx
---
apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            auth_basic "Restricted";
            auth_basic_user_file /etc/secret/.htpasswd;

            proxy_pass http://weyl:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_connect_timeout 1h;
            proxy_send_timeout    1h;
            proxy_read_timeout    1h;
        }

        location /_status {
            return 200 'gangnam style!';
        }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: platform
---  
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx-deployment
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d
            - name: secret-volume
              mountPath: /etc/secret
          readinessProbe:
            # an http probe
            httpGet:
              path: /_status
              port: 80
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
        - name: secret-volume
          secret:
            secretName: basic-auth
