apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: platform
  labels:
    component: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    component: nginx
