apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            auth_basic "Restricted";
            auth_basic_user_file /etc/secret/.htpasswd;

            proxy_pass http://weyl:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_connect_timeout 1h;
            proxy_send_timeout    1h;
            proxy_read_timeout    1h;
        }

        location /_status {
            return 200 'gangnam style!';
        }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: platform
