apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: platform
  labels:
    component: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    component: postgres
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
  namespace: platform
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zones: europe-west1-b
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres
  namespace: platform
  labels:
    component: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        component: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: dilectic
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: 4Gi
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
      annotations:
        volume.beta.kubernetes.io/storage-class: ssd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi