apiVersion: v1
kind: Service
metadata:
  name: weyl
  namespace: {{stack.name}}
  labels:
    component: weyl
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: default
  - port: 8081
    protocol: TCP
    name: admin
  - port: 9999
    protocol: TCP
    name: jmx
  selector:
    component: weyl
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: weyl
  namespace: {{stack.name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: weyl
    spec:
      containers:
        - name: weyl
          image: eu.gcr.io/quartictech/weyl:{{stack.platform_version}}
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 9999
          env:
            - name: WEYL_APPLICATION_OPTS
              value: >
                -Ddw.catalogueWatchUrl=ws://catalogue:8090/api/datasets/watch
                -Ddw.cloudStorageUrl=http://management:8100/api
                -Ddw.server.applicationContextPath=/map
                -Xms{{stack.weyl.memory_gb}}g -Xmx{{stack.weyl.memory_gb}}g
                -Dcom.sun.management.jmxremote=
                -Dcom.sun.management.jmxremote.ssl=false
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.management.jmxremote.port=9999
                -Dcom.sun.management.jmxremote.rmi.port=9999
                -Djava.rmi.server.hostname=localhost
            - name: ENABLE_METRICS
            - name: INFLUX_HOST
              value: influxdb.core
            - name: INFLUX_PORT
              value: "8086"
            - name: INFLUX_DB
              value: k8s
            - name: INFLUX_AUTH
              value: root:root
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: "{{stack.weyl.cpu * cluster.cpu_multiplier}}"
            limits:
              memory: {{stack.weyl.memory_gb + 0.5}}Gi
