apiVersion: v1
kind: Service
metadata:
  name: weyl
  namespace: platform
  labels:
    component: weyl
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: default
  - port: 8081
    protocol: TCP
    name: admin
  selector:
    component: weyl
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: weyl
  namespace: platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: weyl
    spec:
      containers:
        - name: weyl
          image: eu.gcr.io/quartictech/weyl:0.2.0-206-g119e660
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: WEYL_APPLICATION_OPTS
              value: -Ddw.catalogueWatchUrl=ws://catalogue:8090/api/datasets/watch -Xms20g -Xmx20g
            - name: ENABLE_METRICS
            - name: INFLUX_HOST
              value: influxdb.core
            - name: INFLUX_PORT
              value: "8086"
            - name: INFLUX_DB
              value: k8s
            - name: INFLUX_AUTH
              value: root:root
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              memory: 20Gi
