---
- name: Create forms directory
  become: true
  file:
    path: /var/forms
    state: directory

- name: Docker login
  become: true
  shell: docker login -u oauth2accesstoken -p "$(gcloud auth print-access-token)" https://eu.gcr.io

- name: Container present
  docker_container:
    name: formistry-test
    state: started
    image: eu.gcr.io/{{ gcloud_project_id }}/formistry:17
    volumes:
      - "/var/forms:/var/formistry"
    ports:
      - "8080:8080"
  become: true