apiVersion: v1
kind: Service
metadata:
  name: jupyter
  namespace: analysis
  labels:
    component: jupyter
spec:
  ports:
  - port: 8888
    protocol: TCP
    name: default
  selector:
    component: jupyter
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: jupyter
  namespace: analysis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: jupyter
    spec:
      containers:
        - name: jupyter
          image: eu.gcr.io/quartictech/jupyter:46
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 1
              memory: 1Gi
          env:
            - name: JUPYTER_GOOGLE_CLOUD_BUCKET
              value: quartictech/jupyter
          command: ["sh", "-c", "shrubbery_update && start-notebook.sh --debug --ip='*' --NotebookApp.token=''"]