apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: dilectic
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: tls-tracker
      hosts:
        - tracker.{{cluster.gcloud.domain_name}}
    - secretName: tls-mock-tracker
      hosts:
        - mock-tracker.{{cluster.gcloud.domain_name}}
  rules:
    - host: tracker.{{cluster.gcloud.domain_name}}
      http:
        paths:
          - path: /upload
            backend:
              serviceName: btraced-tracker
              servicePort: 8080
    - host: mock-tracker.{{cluster.gcloud.domain_name}}
      http:
        paths:
          - path: /upload
            backend:
              serviceName: mock-tracker
              servicePort: 8080
