apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dilectic
  labels:
    component: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    component: nginx
---
apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location ~ /\. {
            deny all;
        }

        # Static files
        location /datasets {
            proxy_pass            http://pogo:8080;
            proxy_http_version    1.1;

            proxy_connect_timeout 1h;
            proxy_send_timeout    1h;
            proxy_read_timeout    1h;

            client_max_body_size  512m;
        }

        location /tayo {
            proxy_pass            http://tayo:8080;
            proxy_http_version    1.1;
            proxy_set_header      Upgrade $http_upgrade;
            proxy_set_header      Connection "upgrade";

            proxy_connect_timeout 1h;
            proxy_send_timeout    1h;
            proxy_read_timeout    1h;
        }

        location /tracker {
            proxy_pass            http://tracker:8080;
            proxy_http_version    1.1;
            proxy_set_header      Upgrade $http_upgrade;
            proxy_set_header      Connection "upgrade";

            proxy_connect_timeout 1h;
            proxy_send_timeout    1h;
            proxy_read_timeout    1h;
        }

        location /national-grid {
            proxy_pass            http://national-grid:8080;
            proxy_http_version    1.1;
            proxy_set_header      Upgrade $http_upgrade;
            proxy_set_header      Connection "upgrade";

            proxy_connect_timeout 1h;
            proxy_send_timeout    1h;
            proxy_read_timeout    1h;
        }

        location /_status {
            return 200 'gangnam style!';
        }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dilectic
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx
  namespace: dilectic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              cpu: 10m
            limits:
              memory: 64M
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
