apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location ~ /\. {
            deny all;
        }

        # Static files
        location /datasets {
            alias /datasets;
            try_files $uri $uri/ =404;
        }

        location /_status {
            return 200 'gangnam style!';
        }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dilectic
