apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dilectic
  labels:
    component: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    component: postgres
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  namespace: dilectic
  labels:
    name: postgres-data
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{cluster.gcloud.cluster_name}}-dilectic-postgres
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data-claim
  namespace: dilectic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: postgres
  namespace: dilectic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: mdillon/postgis
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: dilectic
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql-data
          resources:
            limits:
              memory: 4Gi
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-claim
