apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  namespace: dilectic
  labels:
    name: postgres-data
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: postgres-data-1
    fsType: ext4
