apiVersion: v1
kind: Service
metadata:
  name: weyl-{{stack.name}}
  namespace: fringe
  labels:
    component: weyl
  annotations:
    quartic.io/healthcheck_path: /healthcheck
    quartic.io/healthcheck_port: "8081"
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: default
  - port: 8081
    protocol: TCP
    name: admin
  - port: 9999
    protocol: TCP
    name: jmx
  selector:
    component: weyl-{{stack.name}}
---
apiVersion: v1
data:
  weyl.yml: |
    catalogue:
      hostname: catalogue.platform
      port: 8090
      useSsl: false
    howlStorageUrl: http://howl.platform:8120/api
    rainWsUrlRoot: ws://rain:8150/ws
    importNamespaceRules:
      open-source: {{stack.weyl.open_source_tags}}
      {{stack.name}}: []
    exportNamespace: weyl-export
    map:
      lat: {{stack.weyl.location.lat}}
      lng: {{stack.weyl.location.lng}}
      zoom: {{stack.weyl.location.zoom}}
    server:
      applicationContextPath: /map
      applicationConnectors:
        - type: http
          port: 8080
      adminConnectors:
        - type: http
          port: 8081
kind: ConfigMap
metadata:
  namespace: fringe
  name: weyl-config-{{stack.name}}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: weyl-{{stack.name}}
  namespace: fringe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: weyl-{{stack.name}}
    spec:
      containers:
        - name: weyl
          image: eu.gcr.io/quartictech/weyl:{{cluster.platform_version}}
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 9999
          volumeMounts:
            - name: config
              mountPath: /weyl-application-{{cluster.platform_version}}/weyl.yml
              subPath: weyl.yml
          env:
            - name: MASTER_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: master_key_base64
            - name: WEYL_APPLICATION_OPTS
              value: >
                -Xms{{(cluster.memory_multiplier * stack.weyl.memory_gb)|round|int}}g -Xmx{{(cluster.memory_multiplier * stack.weyl.memory_gb)|round|int}}g
                -Dcom.sun.management.jmxremote=
                -Dcom.sun.management.jmxremote.ssl=false
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.management.jmxremote.port=9999
                -Dcom.sun.management.jmxremote.rmi.port=9999
                -Djava.rmi.server.hostname=localhost
          resources:
            requests:
              cpu: "{{stack.weyl.cpu * cluster.cpu_multiplier}}"
            limits:
              memory: {{(cluster.memory_multiplier * stack.weyl.memory_gb) + 1.0}}Gi
      volumes:
        - name: "config"
          configMap:
            name: "weyl-config-{{stack.name}}"
