apiVersion: v1
kind: Service
metadata:
  name: zeus-{{stack.name}}
  namespace: fringe
  labels:
    component: zeus
  annotations:
    quartic.io/healthcheck_path: /healthcheck
    quartic.io/healthcheck_port: "8161"
spec:
  ports:
  - port: 8160
    protocol: TCP
    name: default
  - port: 8161
    protocol: TCP
    name: admin
  selector:
    component: zeus-{{stack.name}}
---
apiVersion: v1
data:
  zeus.yml: |
    datasets:
      {{stack.zeus.datasets | indent(6)}}
    url:
      port: 8160
kind: ConfigMap
metadata:
  namespace: fringe
  name: zeus-config-{{stack.name}}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zeus-{{stack.name}}
  namespace: fringe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: zeus-{{stack.name}}
    spec:
      containers:
        - name: zeus
          image: eu.gcr.io/quartictech/zeus:{{cluster.platform_version}}
          ports:
            - containerPort: 8160
            - containerPort: 8161
          env:
            - name: MASTER_KEY_BASE64
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: master_key_base64
            - name: JAVA_OPTS
              value: -Xmx1g
          volumeMounts:
            - name: config
              mountPath: /zeus-backend-{{cluster.platform_version}}/zeus.yml
              subPath: zeus.yml
      volumes:
        - name: "config"
          configMap:
            name: "zeus-config-{{stack.name}}"
