apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: backups
  labels:
    component: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    component: postgres
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: postgres
  namespace: backups
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.4.13
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: 100Mi
              cpu: 100m