project_name                = "Quartic - Production env"
project_id_prefix           = "quartic-prod"
region                      = "europe-west1"
dns_name                    = "global.quartic.io."          # TODO - remove "global"
dns_ttl                     = 60
cluster_name                = "prod"
cluster_core_node_count     = 1
cluster_worker_node_count   = 1
container_developer_group   = "core@quartic.io"             # TODO - this can't be true long-term